FROM consul:1.2.2

COPY docker-entrypoint.sh /tmp/docker-entrypoint.sh

RUN  sed -i "s#consul:x:1000:consul#consul:x:1004:consul#g" /etc/group \
 && sed -i "s#consul:x:100:1000:Linux User,,,:/home/consul:/bin/false#consul:x:1004:1004:Linux User,,,:/home/consul:/bin/false#g" /etc/passwd
 && chown default:default /tmp/docker-entrypoint.sh \
 && chmod +x /tmp/docker-entrypoint.sh 


USER consul
ENTRYPOINT ["/tmp/docker-entrypoint.sh"]
CMD ["agent", "-dev", "-client", "0.0.0.0"]