FROM consul:1.2.2

COPY docker-entrypoint.sh /tmp/docker-entrypoint.sh
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
 && apk add --no-cache shadow  \
 && rm -rf /var/cache/apk/* \
 && groupmod -g 1004 consul \
 && usermod -u 1004 consul  \
 && chown consul:consul /tmp/docker-entrypoint.sh \
 && chmod +x /tmp/docker-entrypoint.sh



USER consul
ENTRYPOINT ["/tmp/docker-entrypoint.sh"]
CMD ["agent", "-dev", "-client", "0.0.0.0"]
